Step2 - 로또(자동)
next-step/swift-lotto pull request #2
Opened 2021-11-11 13:09 UTC by mephrine

안녕하세요 리뷰어님!

요번 과제도 나름 열심히 해봤는데...
생각보다 테스트 Coverage가 낮게 나온 것 같습니다 😭

요번 과제도 잘 부탁드리겠습니다!! 🙇

2021-11-12 15:37 UTC, uuu1101 requested changes
안녕하세요 ! 많은 테스트 케이스를 다뤄보셨네요 ! 👏
네이밍도 상세하게 적혀있어서 파악하는데 좋았어요.

몇가지 코멘트를 남겨두었으니 확인 부탁드립니다. 🙇🏻‍♂️

README.md 에 적힌 입력값에 대한 처리를 보고 한번 실행해 보았습니다.

> 로또 금액보다 적은 금액을 입력 하였을 경우 : 로또는 1000원부터 구매할 수 있습니다. 라는 에러 메세지를 출력하고 있습니다 👍
> 입력값이 음수인 경우: 유효하지 않은 입력입니다.를 출력하고 있습니다. (음수에 대한 경우를 따로 구분을 해두고 계시진 않더라구요)
> 입력값이 숫자가 아닌경우 : 저는 한글 `ㅇ` 를 입력해 보았는데, 위 메세지가 차례대로 출력되고 있더라구요. 이부분도 수정이 필요해 보입니다.

추가적으로 입력값에 대한 처리가 조금 더 있으면 좋을 것 같다고 생각들었던 점은 (**해당 부분을 구현하라는 뜻은 아닙니다 😊**)
지난주 당첨번호를 입력 받을 때 관련해서 
- whiteSpace 를 처리하는게 있으면 더 좋을 것 같단 생각이 들었어요.
> 예를 들어 [2,3, 4,5,6,7]과 [2,3,4,5,6,7 ] 은 정상 작동하지만 [2,3,4 ,5,6,7] 이나 [ 2,3,4,5,6,7] 은 잘못된 입력이라고 분류되고 있습니다.
- 중복된 숫자나 유효하지 않은 입력에 대한 에러가 좀 더 세분화 되었으면 어떨까라는 생각이 들었어요.
> 중복된 숫자가 있다거나, 6개가 아닌 숫자 등 많은 에러상황이 있을 수 있겠네요.

코드를 보면서 실제 로또 판매점과 구매자가 머리에 그려져서 좋았습니다 👍 
구조와 테스트 관련해서 많은 고민을 하신것 같아요. 고생하셨습니다.👏👏

2021-11-12 15:37 UTC, uuu1101 commented on Lotto/Lotto/Lotto/Options/LottoOption.swift
> +	static let lottoAmount: Int = 1000
LottoOption 이라서 lottoNumberRange의 lotto는 생략해도 괜찮을것 같은데 어떻게 생각하세요?! 🤔
다른 프로퍼티 명에도 적용이 될 것 같네요 🙂

2021-11-12 15:37 UTC, uuu1101 commented on Lotto/Lotto/Lotto/RandomNumberGenerator.swift
> +		!numbers.contains(numberOfCheck)
! 를 써도 상관은 없지만, 가독성을 위해서 다르게 변경해보는건 어떨까요?!🤔

2021-11-12 15:37 UTC, uuu1101 commented on Lotto/Lotto/Lotto/Views/InputView.swift
> +	func read(completion: (WinningLotto) -> Void) throws {
read 로 네이밍 하신 이유가 궁금합니다 👀

2021-11-12 15:37 UTC, uuu1101 commented on Lotto/Lotto/extensions/Double+Extension.swift
> +		(floor(self * 100)) / 100
소수점 2자리를 이하를 **내림**처리해주신 이유가 있을까요?!👀

2021-11-12 15:37 UTC, uuu1101 commented on Lotto/LottoTest/LottoTest.swift
> +		let lotteryTickes = lottoMachine
`lotteryTickes` 오타가 있으신거 같습니다 :)

2021-11-12 15:37 UTC, uuu1101 commented on Lotto/LottoTest/LottoTest.swift
> +		let lotteryTickes = lottoMachine
`let lotteryTickes = lottoMachine`
티켓들에 머신을 할당하는 느낌이라 조금 어색해 보일수도 있을 것 같아요. 어떻게 생각하시나요?🤔

2021-11-13 04:05 UTC, mephrine commented on Lotto/Lotto/Lotto/Options/LottoOption.swift
> +	static let lottoAmount: Int = 1000
네! 저도 말씀주신 부분처럼 하는게 중복의 의미도 없어져서 더 좋을 것 같습니다👍

2021-11-13 04:11 UTC, mephrine commented on Lotto/Lotto/Lotto/RandomNumberGenerator.swift
> +		!numbers.contains(numberOfCheck)
오.. 항상 앞에 `!`를 붙여서 사용을 했었는데
`numbers.contains(numberOfCheck) == false`
말씀주신대로 변경을 해보니 가독성이 훨씬 좋아진 것 같아요! 🤭

2021-11-13 04:14 UTC, mephrine commented on Lotto/Lotto/extensions/Double+Extension.swift
> +		(floor(self * 100)) / 100
Step2의 실행 결과 예시 화면에서
총 수익률을 0.35로 표기하신 것을 보고 적용해보았습니다!

2021-11-13 04:26 UTC, mephrine commented on Lotto/Lotto/Lotto/Views/InputView.swift
> +	func read(completion: (WinningLotto) -> Void) throws {
`InputView`의 입장에서 보았을 때,
입력받을 값을 **읽으라는 의미**로 네이밍을 해봤습니다

`read`라고만 되어있다보니 현재 어떤 것을 읽는지 헷갈리는 것 같아서,
`readAmount`, `readWinningNumber`로 변경해보았습니다!

2021-11-13 04:35 UTC, mephrine commented on Lotto/LottoTest/LottoTest.swift
> +		let lotteryTickes = lottoMachine
오타 찾아주셔서 감사합니다 😱😱😱😱😱

넵 저도 약간 어색해보이는 것 같아서,
로또 머신에서 자동 뽑기한 것을 로또에 할당한다는 의미로 변경해보았습니다!
`let lotto = lottoMachine.quickPicks(for: 2)`

2021-11-13 05:24 UTC, mephrine commented
안녕하세요 리뷰어님!
코멘트 달아주신 부분들과,
리뷰요청에 남겨주신 수정 및 요청 사항들을 수정해보았습니다! 🙇

2021-11-15 00:31 UTC, uuu1101 approved these changes
고생하셨습니다 :) 👏👏
다음 스텝 진행하시면 될 것 같아요.
PR에  진행하시면서 생겼던 고민거리나 같이 해결해 볼 고민거리도 적어주시면 더 좋을 것 같습니다👍

2021-11-15 00:31 UTC, merged