mansa pr
next-step/swift-lotto pull request #22
Opened 2022-05-10 12:45 UTC by ITzombietux

레이싱카 미션 떄 Mock객체를 사용했었는데 테스트 커버리지가 좀 떨어지는 현상이 생겼어서 어쩔 수 없이 진짜 객체(?) 테스트를 진행할 수 밖에 없었는데, 아마 제가. Mock객체를 제대로 사용하는 법을 몰라서 그런거 같네요! 이 부분을 좀 더 공부를 하고 반영을 해보도록 하겠습니다..!!

2022-05-11 09:12 UTC, uuu1101 requested changes
고생하셨습니다. 👍🏻👍🏻
먼저 네이밍이나 오탈자 부분에 대해서만 먼저 코멘트 달아두었습니다.


현재 로직에서 로또를 수동으로 입력받고 입력받은 로또를 자동으로 구매한 로또와 함께 출력해줄 때
수동으로 입력받은 로또는 포함되지 않고 출력되고 있습니다. 👀

로또 당첨자 체크 해주는 로직에 문제가 있어보입니다.
지난주 당첨번호를 입력하여도 수동, 자동 로또와 비교하지 못하고 모두 0개 당첨으로 나오고 있어요.😂

반면에 테스트코드는 현재 모두 통과가 되고 있네요. 

해당부분 로직을 한번 확인해주시면 감사하겠습니다 🙇🏻‍♂️

2022-05-11 09:12 UTC, uuu1101 commented on Lotto/Lotto/Lotto/LottoInputView.swift
> +    static func readManualLotto(manualNumber: Int) -> [String] {
```suggestion
    static func readManualLotto(number: Int) -> [String] {
```
manual 이 중복되어, number로만 표현해도 괜찮아보여요.😊

2022-05-11 09:12 UTC, uuu1101 commented on Lotto/Lotto/Lotto/LottoInputView.swift
> +    static func readManualNumber() -> Int {
수동으로 구매할 로또의 개수를 어떻게 표현할수있을까요?
지금은 그냥 수동번호를 읽어오는 느낌이라, 로또 갯수보다는 로또의 번호라는 의미에 더 가깝게 느껴져요 👀

2022-05-11 09:12 UTC, uuu1101 commented on Lotto/LottoTest/LottoTest.swift
> +        let user = User(userLotto: userLotto, center: cener)
```suggestion
        let cetner = LottoCenter(winningLotto: winningLotto)
        let user = User(userLotto: userLotto, center: cetner)
```

2022-05-11 09:12 UTC, uuu1101 commented on Lotto/LottoTest/LottoTest.swift
> +        let user = User(userLotto: userLotto, center: cener)
```suggestion
        let center = LottoCenter(winningLotto: winningLotto)
        let user = User(userLotto: userLotto, center: center)
```
오탈자가 있는것 같아요 👀

2022-05-11 09:44 UTC, ITzombietux commented
에러처리 코드 커밋이 반영이 안된게 있어서 우선은 반영했구요 ㅠㅠ..! 네이밍 부분을 좀 더 신경썼어야 했는데 디테일 신경써주셔서 감사합니다.!! 당첨 로직이 잘 되고 있긴 한데,,! 혹시 한번만 확인을 부탁드립니다!

<img width="671" alt="스크린샷 2022-05-11 오후 6 37 51" src="https://user-images.githubusercontent.com/39956881/167820247-296c8f74-6e82-4c73-ad5f-f56bf80ed1eb.png" width="200" height="300">

2022-05-12 09:23 UTC, uuu1101 requested changes
정상적으로 잘 작동하고 있네요.👍🏻👍🏻
에러처리에 대한 부분 때문에 잘못된 값을 입력 하였을때도 다음 로직으로 진행되어 발생했던 오류인것 같습니다.🙇🏻‍♂️

요구사항에 해당되는 사항은 아니지만, 실제로 프로그램을 실행하였을 때 몇가지 추가,수정되면 좋을것 같은 부분들이 있어서 의견 남깁니다.😊

- ### 잘못된 수동번호를 입력하였을 때
<img width="419" alt="스크린샷 2022-05-12 오후 6 10 04" src="https://user-images.githubusercontent.com/49808034/168035424-f9a37490-6472-4e82-b849-a164ef68153e.png">
구매 완료했다는 문구와 함께 에러처리 문구도 함께 노출되고 있습니다. 
크리티컬하진 않지만 수정되면 더욱 좋을 것 같네요 😊   


- ### 당첨번호에 잘못된 포맷으로 입력된 경우 
<img width="431" alt="스크린샷 2022-05-12 오후 6 12 03" src="https://user-images.githubusercontent.com/49808034/168036084-190a55ae-5378-4ef7-9ef5-e278361d162c.png">
당첨번호를 다시 입력받는게 아니라, 처음부터 다시 시작되고 있어요 👀  

- ### 수동구매에 똑같은 번호를 입력하였을 경우
<img width="376" alt="스크린샷 2022-05-12 오후 6 21 30" src="https://user-images.githubusercontent.com/49808034/168037697-027caf56-0d06-4e78-8e18-a7df3fe56e04.png">

해당부분에 대해서도 오류처리를 해주면 좋을 것 같다는 생각을 해보았습니다 😊

2022-05-12 09:23 UTC, uuu1101 commented on Lotto/Lotto/Lotto/LottoInputView.swift
> +    static func readNumberOfManualPurchase() -> Int {
```suggestion
    static func readManualPurchaseCount -> Int {
```
는 어떨까 하고 저는 생각해보았습니다 😊

2022-05-12 10:57 UTC, ITzombietux commented
너무 디테일한 피드백 감사합니다..! 에러처리를 조금 수정했는데, 지금 로직에서 처음부터 시작하지 않고 에러가 생긴 부분부터 다시 시작하는 것에 대해서는 조금 시간이 걸리지 않을까 해서요 !! 좀 더 클린하게 만들고 싶은 마음에 ㅎㅎㅎ.. 우선은 여기까지 한번 봐주시면 감사하겠습니다~!!

2022-05-13 06:58 UTC, uuu1101 requested changes
수정된 로직에 문제점이 있어서 코멘트 남겨두었습니다 !

~~혹시, 추가적인 작업없이 현재까지의 로직으로만 피드백을 원하시는걸까요?! 😊~~ 제가 잘못읽었군요..💦
추후 진행하시면서 PR요청 해주시면 될 것 같습니다!

2022-05-13 06:58 UTC, uuu1101 commented on Lotto/Lotto/Lotto/LottoSeller.swift
> +
이렇게 체크해버리면, 중복과 관계없이 숫자가 5개 이상이 되었을 때 해당 에러를 표시하게 되지 않을까요? 👀
<img width="395" alt="스크린샷 2022-05-13 오후 3 56 19" src="https://user-images.githubusercontent.com/49808034/168228227-b6c960a2-c95a-44c8-9cd6-4ea016a8f427.png">

6개를 초과하는 7개의 숫자를 입력할때에도 해당 문구가 출력될 것 같습니다 !

2022-05-13 07:40 UTC, uuu1101 requested changes
중복검사에 대한 부분이 이뤄지고 있는지 확인해보셔야 할 것 같습니다. 👀

2022-05-13 07:40 UTC, uuu1101 commented on Lotto/Lotto/Lotto/LottoSeller.swift
> +        guard manualUserLotto.count == 6 else { throw LottoError.duplicateInput }
이렇게 하면 중복과 상관없이 다른 6개의 숫자가 입력 되어도 해당 에러를 출력하게 될 것 같아요.
`readManualLotto(number: Int)` 또는 수동 구매에 대한 입력받은 로또 번호를 `sellLotto`로 넘겨주기 전에 중복 검사가 필요할것 같아요.

2022-05-17 08:36 UTC, uuu1101 approved these changes
고생하셨습니다. 🙇🏻‍♂️
테스트 코드에 통과하지 못하는 케이스가 있습니다 !
확인 부탁드립니다.

<img width="254" alt="스크린샷 2022-05-17 오후 5 35 54" src="https://user-images.githubusercontent.com/49808034/168767939-65c04568-49b8-490b-adb2-94977e281f62.png">

2022-05-17 08:36 UTC, uuu1101 commented on Lotto/LottoTest/LottoTest.swift
> +        let result: [Int] = try! StringUtiltity.splitLottoNumbers(to: input)
```suggestion
        let result: Set<Int> = try! StringUtiltity.splitLottoNumbers(to: input)
```
`splitLottoNumbers(to: input)`의 반환 타입이 수정되어 이 부분도 수정이 필요할 것 같습니다.

2022-05-25 11:35 UTC, uuu1101 approved these changes
고생하셨습니다 ! 👏🏻👏🏻👏🏻

2022-05-25 11:35 UTC, merged