Step2 - Lotto
next-step/swift-lotto pull request #23
Opened 2022-05-11 16:05 UTC by brianeunseokjeon

## 객체 설명
MVC 로 나누어 보았습니다.
로또 Step2 단계입니다.
피드백 주시면 제가 하나하나 수정해보겠습니다!

## 고민
1. 만들다 보니 어느순간 TDD 연습을 하는건지.. 아니면 주어진 과제의 기능을 만드는데 초점을 맞추는건지 이게 지금 TDD 연습을 잘 하고 있는건지 의문이 드네요..

2. 각 객체의 역할을 나눠봤는데, winningStatistic 에서 결과를 보여줘도 되는데, 뭔가 굳이 resultView를 만들어서 한번 더 감싼 느낌이 드는데 이렇게 하는게 맞는건지 의문이 드네요.

3. text들을 하나에서 관리하고 싶었는데, 몇개를 구매했습니다.에서 몇을 모르는 상황, 총 수익률을 땡땡땡 입니다. 라고할때 땡땡땡은 텍스트 자체가 알수 없으니 하나에서 관리하기 힘들던데 더 좋은 방법이 있을까요???

4. ResultView 내부에 match 라는 함수가 있는데 이 함수는 로또들을 통계에 넣어주는 역할을 하는데, 이게 여기서 호출되는게 맞는지.. 더 좋은 방법이 있는지 궁금합니다. ( resultView는 보여주는 역할을 하는 뷰인데, 이 메서드는 모델에 데이터를 넣어주는 역할이라 고민되었습니다 )

2022-05-12 11:05 UTC, uuu1101 requested changes
안녕하세요 ! 고생하셨습니다.👍🏻
몇가지 코멘트 남겨두었습니다. 확인해주세요 ! 
고민점들을 남겨주셨는데요, 거기에 대해서 제 생각을 남겨보겠습니다 🙇🏻‍♂️

1. 만들다 보니 어느순간 TDD 연습을 하는건지.. 아니면 주어진 과제의 기능을 만드는데 초점을 맞추는건지 이게 지금 TDD 연습을 잘 하고 있는건지 의문이 드네요..
>  TDD 참 어려운것 같습니다.. 항상 어디에 초점이 두고 있는건지 의문이 드는 상황이 많으실텐데요. 
시간이 조금 걸리더라도 , 내가 구현해야할 기능이 어떤 것이고, 그럼 어떤 테스트를 해야할지 먼저 작성을 해보고 구현에 들어가보시는건 어떨까요..?! 구현에 필요한 테스트를 작성을 하고 있는지, 테스트를 하기 위해 구현을 하고 있는지에 대해서도 한번 생각해보시면 좋을것 같습니다.

2. 각 객체의 역할을 나눠봤는데, winningStatistic 에서 결과를 보여줘도 되는데, 뭔가 굳이 resultView를 만들어서 한번 더 감싼 느낌이 드는데 이렇게 하는게 맞는건지 의문이 드네요.

> 제 생각은 반대로, resultView가 결과를 보여주는 객체라고 생각이 됩니다. winning에서 결과값을 출력하는 부분이 있던데, 이 부분을 resultView가 가지는건 어떨까요?

3. text들을 하나에서 관리하고 싶었는데, 몇개를 구매했습니다.에서 몇을 모르는 상황, 총 수익률을 땡땡땡 입니다. 라고할때 땡땡땡은 텍스트 자체가 알수 없으니 하나에서 관리하기 힘들던데 더 좋은 방법이 있을까요???
> 음, 이러한 구현방식이 옳은것인지는 모르겠지만..💦
<img width="478" alt="스크린샷 2022-05-12 오후 7 59 30" src="https://user-images.githubusercontent.com/49808034/168055974-11a256b9-9ca0-4326-984b-5119ff85e034.png">
<img width="607" alt="스크린샷 2022-05-12 오후 8 00 30" src="https://user-images.githubusercontent.com/49808034/168056148-a76488d0-ccdd-476f-80b1-bca5ec83ed0a.png">
이렇게 문자열을 관리하는 enum 타입을 두고 관리해보시는건 어떨까요..? 👀
<img width="359" alt="스크린샷 2022-05-12 오후 8 00 56" src="https://user-images.githubusercontent.com/49808034/168056213-d6f6c0e8-beaf-4808-8670-8faeb1946928.png">
결과는 위 이미지처럼 나왔습니다.

- 현재 수익률이 잘못계산되어 표기되는 것 같아요. 확인 부탁드립니다 🙇🏻‍♂️

4. ResultView 내부에 match 라는 함수가 있는데 이 함수는 로또들을 통계에 넣어주는 역할을 하는데, 이게 여기서 호출되는게 맞는지.. 더 좋은 방법이 있는지 궁금합니다. ( resultView는 보여주는 역할을 하는 뷰인데, 이 메서드는 모델에 데이터를 넣어주는 역할이라 고민되었습니다 )
> 개인적인 의견을 드리자면, 로또와 당첨번호가 맞는지 확인하는 새로운 객체를 생성하거나, 통계를 넣어준다고 말씀하셨는데 그렇다면 통계를 담당하는 객체가 가지고 있어야 할것 같습니다. 👀

2022-05-12 11:05 UTC, uuu1101 commented on Lotto/Lotto/Lotto/Model/Winning.swift
> +    var price: Int {
price라고 네이밍을 하신 이유가 궁금합니다 👀

2022-05-12 11:05 UTC, uuu1101 commented on Lotto/Lotto/Lotto/Model/Lotto.swift
> +        var generateNumbers: Set<Int> = []
프로퍼티명이 명사로 시작하여 어색한것 같습니다. 👀

2022-05-12 11:05 UTC, uuu1101 commented on Lotto/Lotto/Lotto/Model/WinningStatistic.swift
> +    func winningResultPrint() {
결과를 출력해주는 부분은 ResultView가 가지고 있는건 어떨까요? 👀

2022-05-12 11:05 UTC, uuu1101 commented on Lotto/LottoTest/LottoTest.swift
> +        let resultWinning = winningStatistic.match(numbers: [1,2,3,4,5,6])
‼️ winningStatistic이 match 메서드를 가지고 있지 않은것 같습니다.

2022-05-13 14:21 UTC, brianeunseokjeon commented on Lotto/LottoTest/LottoTest.swift
> +        let resultWinning = winningStatistic.match(numbers: [1,2,3,4,5,6])
그렇네요 ㅋㅋ 테스트 먼저 짜고 진행했었는데 메서드가 옮겨졌네요

2022-05-13 14:42 UTC, brianeunseokjeon commented on Lotto/Lotto/Lotto/Model/WinningStatistic.swift
> +    func winningResultPrint() {
수정해 보았습니다 ~

2022-05-13 14:44 UTC, brianeunseokjeon commented on Lotto/Lotto/Lotto/Model/Lotto.swift
> +        var generateNumbers: Set<Int> = []
프로퍼티는 명사여야 하는데, 동사로 시작한게 이상하다는 걸까요??

2022-05-13 15:27 UTC, brianeunseokjeon commented on Lotto/Lotto/Lotto/Model/Winning.swift
> +    var price: Int {
prize 라고했어야했는데 헷갈렸네요. reward 라고 수정해보았습니다

2022-05-13 15:31 UTC, brianeunseokjeon commented on Lotto/Lotto/Lotto/Model/Lotto.swift
> +        var generateNumbers: Set<Int> = []
numbers 로 수정했습니다.

2022-05-13 15:46 UTC, brianeunseokjeon commented on Lotto/Lotto/Lotto/Model/Lotto.swift
> +        var generateNumbers: Set<Int> = []
[b42b13b](https://github.com/next-step/swift-lotto/pull/23/commits/b42b13b3e157031767c8fe79c0d4100d3c4b3f5b)

2022-05-13 15:46 UTC, brianeunseokjeon commented on Lotto/Lotto/Lotto/Model/Winning.swift
> +    var price: Int {
[851f581](https://github.com/next-step/swift-lotto/pull/23/commits/851f581430adb676128b016f87e124aea79c32e7)

2022-05-13 15:46 UTC, brianeunseokjeon commented on Lotto/LottoTest/LottoTest.swift
> +        let resultWinning = winningStatistic.match(numbers: [1,2,3,4,5,6])
[2c7af1c](https://github.com/next-step/swift-lotto/pull/23/commits/2c7af1c136a422b41e298ed308e60c578ca0bff3)

2022-05-13 15:46 UTC, brianeunseokjeon commented on Lotto/Lotto/Lotto/Model/WinningStatistic.swift
> +    func winningResultPrint() {
[6706157](https://github.com/next-step/swift-lotto/pull/23/commits/670615734d0a14afa7871453658114d190d15e11)

2022-05-14 08:36 UTC, uuu1101 commented on Lotto/Lotto/Lotto/Model/Lotto.swift
> +        var generateNumbers: Set<Int> = []
아, 네 동사로 시작하는게 어색하다는거 였습니다. 제가 잘못 코멘트를 남겨두었네요 💦

2022-05-14 13:53 UTC, uuu1101 approved these changes
고생하셨습니다.😊
테스트 코드를 실행해보시면 `LottoGuide`를 찾지못하고 있습니다.
Targets > BuildPhases > Compile Sources 를 추가해주셔야 할 것 같아요.

2022-05-14 13:53 UTC, merged